script for deleting test environment
dataquest-dev/DSpace pull request #109
Opened 2022-08-02 11:10 UTC by Paurikova2

| Phases            | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -   |   -     |        0 |
## Problem description
### Reported issues
### Not-reported issues
## Analysis
(Write here, if there is needed describe some specific problem. Erase it, when it is not needed.)
## Problems
(Write here, if some unexpected problems occur during solving issues. Erase it, when it is not needed.)

2022-08-03 15:27 UTC, MajoBerger requested changes
why not use already used env file? Just add
`set m_2 source=`

2022-08-04 10:51 UTC, Paurikova2 commented
> 

Because we don't want to do it together with build.script. Or do we want it?

2022-08-04 10:53 UTC, Paurikova2 commented on scripts/run.delete.dspace.parent.bat
> +rem set those to your local paths in .gitignored file /envs/__dspace.parent.basic.bat.
if I understand, now there is no need to write the information there...

2022-08-05 06:47 UTC, MajoBerger commented on scripts/run.delete.dspace.parent.bat
> +rem set those to your local paths in .gitignored file /envs/__dspace.parent.basic.bat.
yes

2022-08-05 06:50 UTC, MajoBerger commented
The way I understand it, in that file that already exists, there are paths to relevant places on each PC. 
All can be in one place I think. Now for example, there is double definition of dspace_source. 
If we continued this way, there would be many different .env files each containing almost the same.
It is certainly bad practice to define the same value multiple times on multiple different locations.

That's why I think there should be only one file with envs...

2022-08-12 10:12 UTC, MajoBerger requested changes
Don't use `__dspace.parent.basic.bat` but `__basic.bat` for envs

2022-08-12 10:12 UTC, MajoBerger commented on scripts/envs/__dspace.parent.basic.example.bat
> +set dspace_source=C:\workspace\DSpace
We agreed to remove this file and use `__basic.example.bat` instead, no?

2022-08-12 10:12 UTC, MajoBerger commented on scripts/run.delete.dspace.parent.bat
> +call envs\__dspace.parent.basic.bat
same as above. use `__basic.example.bat`

2022-08-16 06:32 UTC, MajoBerger approved these changes

2022-08-16 06:34 UTC, merged