75-BE/missing-handles
dataquest-dev/DSpace pull request #314
Opened 2023-06-13 11:54 UTC by Paurikova2

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  5  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description
After handle import, there are missing some handles.

2023-06-16 06:08 UTC, milanmajchrak requested changes

2023-06-16 06:08 UTC, milanmajchrak commented on dspace-api/src/main/java/org/dspace/handle/HandleClarinServiceImpl.java
> +        if (!(StringUtils.isBlank(handleStr))) {
You can use StringUtils.isNotBlank

2023-06-16 06:08 UTC, milanmajchrak commented on dspace-api/src/main/java/org/dspace/handle/HandleClarinServiceImpl.java
> +        if (!authorizeService.isAdmin(context)) {
Only admin? Will never any user use this method during creating an Item? This is only migration purposes right?

2023-06-16 06:08 UTC, milanmajchrak commented on dspace-api/src/main/java/org/dspace/handle/HandleClarinServiceImpl.java
> +
why so much empty rows?

2023-06-16 06:08 UTC, milanmajchrak commented on dspace-api/src/main/java/org/dspace/handle/service/HandleClarinService.java
> +     * Create handle without dspace object.
If this is only for migration purposes please add some note that this is only for migration and for a specific case.

2023-06-16 06:08 UTC, milanmajchrak commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ClarinItemImportController.java
> +     * @return workslaceitem converted to rest
workspace not workslace

2023-06-16 06:08 UTC, milanmajchrak commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/ClarinHandleImportControllerIT.java
> +    public void createHandleTest() throws Exception {
Please describe better what are you testing. Is it that handles without DSpace obejct?

2023-06-19 13:12 UTC, milanmajchrak approved these changes

2023-06-20 19:10 UTC, mrovnanik approved these changes

2023-06-21 06:36 UTC, merged