Tul/tmp 4 merge (#401)
dataquest-dev/DSpace pull request #402
Opened 2023-08-07 11:49 UTC by milanmajchrak

* 97425: Fix issue with sessions null value

* 97061: type request param name change to avoid confusion with rest object type & error codes endpoint changes + IT:
- missing/wrong query param accountRequestType => 400 bad request
- email not valid domain => 422 unprocessable entity

* [CST-7756] refactoring & added missing JavaDoc

* [CST-7756] removed unused service bean

* [CST-7756] minor refactoring  according to the rest contract

* PR #8619: Removed dependency spring-context-support, not needed in main

* [CST-7756] fixed failed tests

* [CST-7756] refactoring

* [CST-7756] added tests to valid subscription parameters

* [CST-7756] added validation logic of params

* [CST-7756] renamed some methods & class

* [CST-7756] minor fix

* [CST-7756] refactored CanSubscribeFeatureIT

* 97425: Implement feedback

* [CST-7756] minor update

* [CST-7756] added missing index field

* [CST-7756] added template for subscription content email

* [CST-7754] removed old code of supervision orders added a new migration script sql
tested that supervisors can edit only workspace items

* [CST-7756] refactoring

* Remove statusFilter added to Solr browse indexes queries to solve an issue with the local administrators navigation

* [CST-7756] monor fix

* [CST-7756] added unit tests covering methods with business logic

* [CST-7756] sub-daily command and its referred class removed, as subscriptions are sent by subscription-send command

* [CST-7756] updated license header

* 97425: Fix minor issues

* [CST-7756] added instructions to migrate subscriptions from previous versions

* [CST-7756] after merge checkstyle fix

* [CST-7756] extended abstract test

* [CST-7756] updated script

* 99053: Add return_to_pool option to all ProcessingAction except SingleUserReviewAction

* Reinstate config accidentally deleted, added in 30f923a080aa0d927036e0eae609c3bf1a273d35 (#8064) - enables RSS/Atom feeds

* [CST-7756] removed subscriptions for items

* [CST-7756] minor fix

* [CST-7756] extended SubscribeServiceTest in order to use service instance with real (h2) database instead of mocks, so that tests actually store, query and remove subscriptions interacting with database

* [CST-7756] added missing JavaDoc

* [CST-7756] code refactoring

* [CST-7756] renamed test class in order to reflect its actual behavior

* [CST-7756] removed mail template used by previous script

* [CST-7756] code refactoring

* [CST-7756] removed Items section

* [CST-7756] added missing IT

* [CST-7754] updated javadoc

* [CST-7754] updated comment

* [CST-7754] withdrawn item should not allow supervision order

* [CST-7754] moved supervision orders test on workflow items to SupervisionOrderRestRepositoryIT, added test covering the scenario when an admin tries to set a supervision order on a withdrawn item, and when an admin sets a supervision order on a workflow item before sending it back to workspace: supervisor can edit the item only when it goes to workspace status.

* [TLC-380] Browse links and "by regex" links in item display

* [TLC-380] Fix checkstyle and duplicate code

* [TLC-380] Further checkstyle fixes

* [TLC-380] Further checkstyle fixes

* [TLC-380] Refactor browses endpoint for browse link usage

* [TLC-249] Improve 'findByFields' browse refactor

* [TLC-380] Fix browse resource byFields IT

* [TLC-380] Remove unused methods, add ITs

* #8629: Make sure temporary worfklow groups of reviewers get deleted

* #8629: PR feedback refactor

* [CST-7756] implemented community feedbacks

* [CST-7756] added test that proves what happens if an object is access restricted after you have a subscription to it.

* [CST-7756] renamed a method

* [CST-7756] updated subscriptions migration scripts

* [CST-7756] removed 'lastModified_dt' index field

* [CST-7756] minor refactoring

* [CST-7756] added email subject

* [CST-7756] added dissemination for generic DSpace Item

* [CST-7756] If no crosswalk is defined for the Item's entity type, default generic Item one is applied

* IT fix: ReviewManagers repository wide group, not collection workflow group

* Test IT without drop constraint

* [CST-7756] restores security check as was originaly

* [CST-7756] described beans

* #8628: Remove GET shortlivedtokens endpoint & related IT

* [TLC-249] Show Identifier Step, pre-register identifiers

* [TLC-249] Remove unused import in WorkspaceItemServiceImpl

* [TLC-249] Update section count test in SubmissionDefinitionsControllerIT

* [TLC-249] Refactor to support better filter usage, PENDING and MINTED status

* [TLC-249] Add and expose config for enabling register DOI

* [TLC-249] REST backend for identifier config

* [TLC-249] Better status return for new DOIs, write new integration tests

* [TLC-249] Integration tests, keep GET handling in controller

* [TLC-249] Move GET handling back to ItemIdentifierController

* [TLC-249] Checkstyle fixes

* [TLC-249] Licence header fixes

* [TLC-249] Further checkstyle fixes

* [TLC-249] Fix tests, Refactor things to use a LinkRestRepository for GET, Controller for POST

* [TLC-249] Further IT fix for identifiers

* [TLC-249] Licence header fix

* [TLC-249] Address review feedback

Controller updated to be less DOI-specific in its
registration implementation
item-status.register renamed to registerDOI
display types included in section data, for UI hints comments / javadoc added
DOI status text sent instead of number in status data

As per tdonohue's revew on 2022-01-18

* [TLC-249] Lint fixes

* [TLC-249] Improve model for identifier step data

* [TLC-249] Update configuration identifiers.cfg

* [TLC-249] Remove unused subclass DataIdentifier

* [TLC-249] Update identifier section IT

* [TLC-249] Update integration tests for identifier controller

* [TLC-249] Fix submission controller IT

* [TLC-249] Update canRegisterDOIFeature to check for cfg enabled

* [TLC-249] Refactor identifiers create endpoint

* [TLC-249] Refactor, include controller 'find DSO' operation

* [TLC-249] Throw not implemented for findOne and findAll

* [TLC-249] Fixes and improvements as per review feedback

* [TLC-249] Checkstyle fix

* [TLC-249] return value  as id for IdentifierRest

* [TLC-249] Fix category type in IdentifierRest

* [TLC-249] Update integration tests for IdentifierRestRepository

* [TLC-249] Refactor TrueFilter to get instantiated as singleton

* [TLC-249] Construct canonical handle URL in identifier item link

* [TL-249] Remove example-doi_filter from config, add singleton attr to TrueFilter

* [TL-249] Add always_true_filter to test REST identifier-service.xml config

* [TL-249] Add identifiers.cfg and item-filters.xml config to test data

* [TL-249] Fix imports

* [TL-249] Revert accidental commit to RestResourceController

* [TL-249] Javadoc and other small fixes, DOI unit tests

* [TL-249] Javadoc and other small fixes

Including stripping $Revision$ from filter javadoc.

* [TL-249] Checkstyle fix

* 99200: Delete items after copies have been requested fix

* [CST-7756] added security check into 'subscription-send' script

* Alternate way to restart workflow in case of decline

* Fix for decline when the delete doesn't persist in context before wfi is created again from same item

* [CST-7754] supervising user can perform operations on Workspace item only if they have proper permissions

* [DURACOM-116] process sorted alphabetically

* [TLC-249] Test abandoning of a pending DOI and minting afterwards

* [TLC-249] Ensure property identifiers.item-status.register-doi is set

* Added missing commit in cleanup method

* Update BitstreamStorageServiceImpl.java

Amend commit log message

* [CST-7756] Non-Discoverable and withdrawn items must be excluded from the notification list

* [DURACOM-116] moved sorting to service

* removed the log info

* CST-8936 fix permission for bitstream generated by media-filter

* Updates to LICENSES_THIRD_PARTY for 7.5

* [maven-release-plugin] prepare release dspace-7.5

* Fixed some compile errors

* Fixed some compile errors

* Fixed so [...]

2023-08-08 07:04 UTC, MajoBerger requested changes
blank line at end of file

2023-08-08 07:04 UTC, MajoBerger commented on dspace/config/clarin-dspace.cfg
> +themed.by.company.name = dataquest s.r.o.
shouldnt here be a blank line

2023-08-08 07:05 UTC, milanmajchrak commented on dspace/config/clarin-dspace.cfg
> +themed.by.company.name = dataquest s.r.o.
Fixed, thank you

2023-08-08 07:06 UTC, MajoBerger approved these changes

2023-08-08 10:37 UTC, merged

2023-09-27 07:29 UTC, milanmajchrak reviewed
q