internal/load-version-from-file
dataquest-dev/DSpace pull request #488
Opened 2023-12-22 14:13 UTC by milanmajchrak

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2023-12-27 13:14 UTC, vidiecan requested changes

2023-12-27 13:14 UTC, vidiecan commented on dspace/config/clarin-dspace.cfg
> +build.version.file.path =
fill this with a link ponting to a file in dspace/config directory named `VERSION_D`

2023-12-27 13:14 UTC, vidiecan commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/RootConverter.java
> +        try (FileReader fileReader = new FileReader(bVersionFilePath);
even if it is filled, check if it exists, if not, do not log anything

2024-01-02 10:42 UTC, vidiecan requested changes

2024-01-02 10:42 UTC, vidiecan commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/RootConverter.java
> +                buildVersion = line;
only one line is read!

2024-01-02 10:55 UTC, milanmajchrak commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/RootConverter.java
> +                buildVersion = line;
Fixed

2024-01-02 16:37 UTC, vidiecan approved these changes

2024-01-02 16:58 UTC, vidiecan approved these changes

2024-01-03 07:13 UTC, merged