ufal/comment-ever-failing-test
dataquest-dev/DSpace pull request #490
Opened 2024-01-04 12:34 UTC by milanmajchrak

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2024-01-04 23:20 UTC, vidiecan requested changes

2024-01-04 23:20 UTC, vidiecan commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/RegistrationRestRepositoryIT.java
> +import org.junit.Ignore;
add why at least to PR

2024-01-05 09:08 UTC, milanmajchrak commented on dspace-server-webapp/src/test/java/org/dspace/app/rest/RegistrationRestRepositoryIT.java
> +import org.junit.Ignore;
I've added info into PR description

2024-01-05 12:39 UTC, vidiecan approved these changes

2024-01-05 12:50 UTC, merged