ufal/s3-check-etag
dataquest-dev/DSpace pull request #537
Opened 2024-02-20 10:06 UTC by milanmajchrak

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2024-02-20 12:31 UTC, vidiecan requested changes

2024-02-20 12:31 UTC, vidiecan commented on dspace-api/src/main/java/org/dspace/storage/bitstore/SyncS3BitStoreService.java
> +        long partSize = 50 * 1024 * 1024; // 50 MB
make this a constant of this class

2024-02-20 12:31 UTC, vidiecan commented on dspace/config/clarin-dspace.cfg
> +upload.by.parts.enabled = true
should have s3 prefix

2024-02-21 12:59 UTC, milanmajchrak commented on dspace-api/src/main/java/org/dspace/storage/bitstore/SyncS3BitStoreService.java
> +        long partSize = 50 * 1024 * 1024; // 50 MB
done

2024-02-21 15:19 UTC, merged