Item has two handles after import
dataquest-dev/DSpace pull request #659
Opened 2024-05-16 14:56 UTC by milanmajchrak

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2024-05-17 06:52 UTC, MajoBerger requested changes
do not condition replacement of handles with this property - up for discission.

2024-05-17 07:05 UTC, milanmajchrak commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ClarinItemImportController.java
> +                .getBooleanProperty("identifiers.submission.register", false) &&
I do not agree. What if Item already has a handle, we sent desired handle and the property `identifiers.submission.register` is set to false (should not have pre-registered handle) and somehow we need to keep that already assigned handle? This fix addresses only the error we are encountering.

2024-05-17 07:10 UTC, MajoBerger commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ClarinItemImportController.java
> +                .getBooleanProperty("identifiers.submission.register", false) &&
Is there a scenario, when we need two handles? And if yes, will the second handle be assigned like this? Not afterwards?

2024-05-20 11:11 UTC, vidiecan approved these changes

2024-05-20 11:29 UTC, MajoBerger commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ClarinItemImportController.java
> +                .getBooleanProperty("identifiers.submission.register", false) &&
@vidiecan @milanmajchrak I do not know what is the current situation, I need to know more to resolve. I expect more comments to answer my question.

Marking this for standup tomorrow.

2024-05-20 13:01 UTC, MajoBerger commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ClarinItemImportController.java
> +                .getBooleanProperty("identifiers.submission.register", false) &&
we agreed verbally, that this solution is ok

2024-05-20 13:01 UTC, merged

2024-05-20 13:01 UTC, MajoBerger approved these changes