UFAL/Enhanced type-bind feature
dataquest-dev/DSpace pull request #762
Opened 2024-09-16 11:48 UTC by milanmajchrak

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2024-09-19 15:00 UTC, vidiecan requested changes

2024-09-19 15:00 UTC, vidiecan commented on dspace-api/src/main/java/org/dspace/app/util/DCInput.java
> +        if (typeBind.size() == 0) {
isEmpty

2024-09-19 15:00 UTC, vidiecan commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/MetadataValidation.java
> +            if (typeBindField.contains("=>")) {
id `=>` somewhere specified, would be great to have it as a constant or similar

2024-10-08 14:43 UTC, vidiecan requested changes

2024-10-08 14:43 UTC, vidiecan commented on dspace-api/src/main/java/org/dspace/app/util/DCInput.java
> +        if (typeBindDef != null && typeBindDef.trim().length() > 0) {
typeBindDef.trim().isEmpty()
@milanmajchrak TT

2024-10-08 14:43 UTC, vidiecan commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/MetadataValidation.java
> +        // Begin the actual validation loop
?

2024-10-11 14:05 UTC, milanmajchrak commented on dspace-api/src/main/java/org/dspace/app/util/DCInput.java
> +        if (typeBindDef != null && typeBindDef.trim().length() > 0) {
changed

2024-10-17 11:51 UTC, vidiecan approved these changes

2024-10-17 12:30 UTC, vidiecan approved these changes

2024-10-17 14:21 UTC, merged