Translation of submission-forms to _cs
dataquest-dev/DSpace pull request #816
Opened 2024-11-20 11:13 UTC by jr-rk

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description
### Reported issues
### Not-reported issues
## Analysis
(Write here, if there is needed describe some specific problem. Erase it, when it is not needed.)
## Problems
(Write here, if some unexpected problems occur during solving issues. Erase it, when it is not needed.)

2024-11-20 13:19 UTC, milanmajchrak requested changes

2024-11-20 13:19 UTC, milanmajchrak commented on dspace/config/submission-forms_cs.xml
> +        <!--/ TRANSLATE THIS -->
Remove this message

2024-11-20 13:19 UTC, milanmajchrak commented on dspace/config/submission-forms_cs.xml
> +        <!-- TRANSLATE THIS -->
Remove

2024-11-20 13:19 UTC, milanmajchrak commented on dspace/config/submission-forms_cs.xml
> +        <!-- THIS -->
Remove

2024-11-20 13:19 UTC, milanmajchrak commented on dspace/config/submission-forms_cs.xml
> +                        Please enter the full path of the file, either from the local server or an HTTP location.
Missing translations

2024-11-20 13:19 UTC, milanmajchrak commented on dspace/config/submission-forms_cs.xml
> +            <input name="givenname" input-type="text" label="Contact person's given name" required="true"/>
Missing translations

2024-11-20 13:19 UTC, milanmajchrak commented on dspace/config/submission-forms_cs.xml
> +                <displayed-value>Yes</displayed-value>
Translate

2024-11-25 10:14 UTC, milanmajchrak submitted a review, later dismissed

2024-11-25 15:35 UTC, vidiecan requested changes

2024-11-25 15:35 UTC, vidiecan commented on dspace/config/submission-forms.xml
> +                    <regex>The supplied url must start with http/https</regex>
?

2024-11-26 09:48 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <regex>The supplied url must start with http/https</regex>
Oh, I didn't realize... Thank you!

2024-11-26 14:16 UTC, vidiecan approved these changes

2024-11-26 16:10 UTC, merged