Facet result for suggestion
dataquest-dev/DSpace pull request #835
Opened 2024-12-20 08:18 UTC by Paurikova2

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2025-01-07 14:30 UTC, milanmajchrak requested changes
Make it NO-case-sensitive

2025-01-07 14:30 UTC, milanmajchrak commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/SuggestionRestController.java
> +            }
Do this also in the MetadataValueRestRepository

2025-01-09 09:29 UTC, Paurikova2 commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/SuggestionRestController.java
> +            }
We cannot use facet here because there is no metadata solar search index for it. But I modified search that for now we get all results, no only the first ten results.

2025-01-09 09:34 UTC, Paurikova2 commented
@milanmajchrak 
The Solr search is case-sensitive. If we want to make it case-insensitive, we need to add a new custom field type that applies a lowercasing filter (https://dev.to/cendekia/perform-case-insensitive-sorting-in-solr-6k4). However, because we don't want to modify the Solr schema and because we don't want to spend time on unnecessary work, I believe that adopting a case-insensitive approach is not necessary for now.

2025-01-09 12:30 UTC, Paurikova2 commented on dspace-api/src/main/java/org/dspace/core/HibernateDBConnection.java
> +                        entity.getID());
This is because of the incorrect check style from dtg-dev branch

2025-01-09 12:30 UTC, Paurikova2 commented on dspace-api/src/main/java/org/dspace/core/HibernateDBConnection.java
> +                        entity.getID());
This is because of the incorrect check style from dtg-dev branch

2025-01-09 12:32 UTC, Paurikova2 commented on dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/MetadataValueRestRepository.java
> +        for (IndexableObject object : searchResult.getIndexableObjects()) {
from 124 to 154 is original code, no changes

2025-01-23 11:45 UTC, milanmajchrak commented
This PR continues here: https://github.com/dataquest-dev/DSpace/pull/854

2025-01-23 12:05 UTC, closed without merging

2025-01-23 12:05 UTC, milanmajchrak commented
This PR continues here: https://github.com/dataquest-dev/DSpace/pull/854