modified submission based on SAV requirements
dataquest-dev/DSpace pull request #837
Opened 2024-12-20 12:35 UTC by Paurikova2

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2025-01-07 11:34 UTC, milanmajchrak requested changes

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <required>You must enter an unambiguous reference to the resource.</required>
I think it is not required

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <hint>An entity responsible for making the resource available.
Why did you change the hint message?

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <hint>The nature or genre of the resource.
Why did you change the hint message?

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> -            </row>
Please keep this

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> -                    <dc-element>contributor</dc-element>
Keep the contibutor author

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> -                    <required>Please add author(s)</required>
with (s) there could be more authors

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <hint>A language of the resource. Multiple languages are possible. Start
Why did you change the hint message?

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <hint>A topic of the resource. Enter appropriate subject keyword or phrase and press the Add button. You can repeat it for
?

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <dc-element>accrualMethod</dc-element>
use local.*

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <dc-schema>dc</dc-schema>
The format is automatically assigned

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <vocabulary>srsc</vocabulary>
Are you sure with srsc vocabulary?

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <vocabulary>srsc</vocabulary>
why srsc?

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <vocabulary>srsc</vocabulary>
why srsc?

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <vocabulary>srsc</vocabulary>
why srsc?

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <vocabulary>srsc</vocabulary>
srsc?

2025-01-07 11:34 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <dc-element>accessRights</dc-element>
Use dc.rights like in the ZCU
https://github.com/dataquest-dev/DSpace/blob/customer/zcu-data/dspace/config/submission-forms.xml#L1214

2025-01-07 13:06 UTC, milanmajchrak requested changes

2025-01-07 13:06 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <label>Contributor</label>
```
                    <dc-schema>dc</dc-schema>
                    <dc-element>contributor</dc-element>
                    <dc-qualifier>author</dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Authors</label>
```

2025-01-07 13:09 UTC, milanmajchrak commented on dspace/config/submission-forms.xml
> +                    <hint>A topic of the resource. Enter appropriate subject keyword or phrase and press the Add button. You can repeat it for
IT2:
@Paurikova2 this hint?

2025-01-07 13:30 UTC, Paurikova2 commented on dspace/config/submission-forms.xml
> +                    <hint>The nature or genre of the resource.
I changed it based on their requirements.

2025-01-07 13:30 UTC, Paurikova2 commented on dspace/config/submission-forms.xml
> +                    <hint>An entity responsible for making the resource available.
I changed it based on their requirements.

2025-01-07 13:30 UTC, Paurikova2 commented on dspace/config/submission-forms.xml
> +                    <hint>A language of the resource. Multiple languages are possible. Start
I changed it based on their requirements.

2025-01-07 13:30 UTC, Paurikova2 commented on dspace/config/submission-forms.xml
> +                    <hint>A topic of the resource. Enter appropriate subject keyword or phrase and press the Add button. You can repeat it for
I changed it based on their requirements.

2025-01-07 13:30 UTC, Paurikova2 commented on dspace/config/submission-forms.xml
> +                    <vocabulary>srsc</vocabulary>
I did not understand its using. It can be used by tag label, no textarea.

2025-01-07 13:30 UTC, Paurikova2 commented on dspace/config/submission-forms.xml
> +                    <vocabulary>srsc</vocabulary>
I did not understand its using. It can be used by tag label, no textarea.

2025-01-07 13:30 UTC, Paurikova2 commented on dspace/config/submission-forms.xml
> +                    <dc-schema>dc</dc-schema>
So I will remove this part of submission form...

2025-01-07 13:30 UTC, Paurikova2 commented on dspace/config/submission-forms.xml
> -            </row>
but why do we want it when it is not in customer requirements?

2025-01-14 13:54 UTC, Paurikova2 commented
https://github.com/dataquest-dev/DSpace/pull/846

2025-01-14 13:54 UTC, closed without merging