Internal/generate bat for tests
dataquest-dev/DSpace pull request #94
Opened 2022-07-14 08:18 UTC by MajoBerger

| Phases            | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |    1 |     0 |      0 |        0 |
| Developing      |  0  |    1 |    0 |      0 |         0 |
| Review             |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -   |   -     |        0 |
## Problem description
Generate .bats for testing based on .yml configuration

2022-07-14 10:20 UTC, milanmajchrak approved these changes

2022-07-14 10:50 UTC, milanmajchrak requested changes

2022-07-14 10:50 UTC, milanmajchrak commented on scripts/envs/__basic.example.bat
>  set dspace_application=C:\dspace\
'No endline at end of file'

2022-07-14 10:50 UTC, milanmajchrak commented on scripts/regenerate.bat
> +java -jar regenerate.jar
'No endline at end of file'

2022-07-14 10:55 UTC, MajoBerger commented on scripts/envs/__basic.example.bat
>  set dspace_application=C:\dspace\
is that problem?

2022-07-15 06:40 UTC, Paurikova2 requested changes
Generates only one file, if there are several tests of same class, one with method name, one without it.

2022-07-15 06:40 UTC, Paurikova2 commented on scripts/regenerate.bat
> +java -jar regenerate.jar
is this necessary?

2022-07-15 06:40 UTC, Paurikova2 commented on scripts/__tests.yaml
> +  - sourceFolder: "dspace-server-webapp"
Add comment e.g. #example one

2022-07-15 06:40 UTC, Paurikova2 commented on scripts/__tests.yaml
> +# copy this file and name it tests.yaml
Add here
"create your own test sets using these commands - not all of them are necessary"

2022-07-15 10:44 UTC, Paurikova2 approved these changes

2022-07-15 10:45 UTC, merged